### ISSUE TITLE
Provider request - parent_process_env

### ISSUE THREAD

**Issue by kevbook** [tellerops/teller#116]
## New Provider Request

Instead of `carry_env` option, we should have a `parent_process_env` provider. So we can selectively load up parent process env vars as needed. It would also allow renaming the field/variable as needed. 

It's very useful if we need to run a docker container:

```bash
$ docker run --rm -it --env-file <(teller env) alpine sh

// Should also will populate the following for various use-cases:
$ teller show
$ teller json
$ teller yaml
```

```yaml
providers:
  parent_process_env:
    env:
      GIT_SHA:

```

## Details
- Name: parent_process_env
- Modes: read

**Comment by kaplanelad** [comment]
Hey @kevbook, just to make sure that i understand your case, 
Your suggestion is allow Teller to read parent environment variable like this example:

```
export SECRET-KEY=<secret value>
```
and the `.teller.yaml` file config will look like:
```
providers:
  parent_process_env:
    env:
      telelr-secret-key: SECRET-KEY
```
