### ISSUE TITLE
Doppler provider does not handle templating correctly

### ISSUE THREAD

**Issue by lukasmrtvy** [tellerops/teller#142]
## Expected Behavior

Doppler provider does handle templating

## Current Behavior

Doppler provider does not handle templating, exiting with:
```
error="yaml: unmarshal errors:\n  line 11: cannot unmarshal !!map into string"
```

## Possible Solution

Fix

## Steps to Reproduce

1.
```
cat << EOF > .teller.yaml
project: apify-app
opts:
  stage: env:STAGE,tellerdoesnothandleexitcodeifenvisunsetusesomesillystringtowarnusers

confirm: Are you sure you want to run in {{stage}}?

providers:
  doppler:
    env:
      MONGODB_PASSWORD:
        path: {{stage}}
        field: MONGODB_PASSWORD
EOF
```
2.
```
teller run
```

## Specifications
  - Version: 1.5.6
  - Platform:
