### ISSUE TITLE
[BUG]: Hashicorp Vault secret mount name can't contain '/'

### ISSUE THREAD

**Issue by yafanasiev** [tellerops/teller#277]
OS: macOS 14.4.1 (23E224) (Intel)
Teller version: 2.0.5

Description:
Given the following sample configuration

```yaml
providers:
  hashicorp_vault:
    kind: hashicorp
    maps:
      - id: test
        path: 'foo/bar/test'
 ```
 
 where `foo/bar` is a secret mount name (including forward slash), and `test` is a secret path, Teller fails with the following error:
 
 ```
 APIError { code: 404, errors: ["no handler for route \"foo/data/bar/test\". route entry not found."] }
Error: NOT FOUND foo/bar/test: not found

Location:
    /private/tmp/teller-20240515-8094-43x90q/teller-2.0.5/teller-cli/src/cli.rs:266:23
```

Judging from request, Teller treats part of the path up to the first slash as a secret mount name and builds the Vault request accordingly, which is incorrect in our case.

I already tried URLencoding the slash character, escaping, double escaping etc.

With Teller v1, the following configuration was working for us:

```
path: foo/bar/data/test
```
