### ISSUE TITLE
Support externally defined providers

### ISSUE THREAD

**Issue by vetsin** [tellerops/teller#280]
So that one may write custom providers of which are 'internal', a good example would be how `docker` does it:

- https://github.com/docker/docker-credential-helpers
- You may configure a provider, e.g. `{ "credsStore": "ecr-login" }`
  - This would use the `ecr-login` provider, as written here: https://github.com/awslabs/amazon-ecr-credential-helper

So in teller world that may be:

```yaml
providers:
  ecr-1: 
    kind: ecr-login
```

or more likely:

```yaml
providers:
  ecr-1:
    kind: credential-helper
    bin: ecr-login
```

The idea being we use use stdin/out from other binaries as the interface, optionally.

Something like `ProviderKind::CredentialHelper` which literally just calls `format!("teller-credential-{} {}", bin, action)`? Albeit without the command injection

This may also allow fancier credential syncing where we may have needed a template before, e.g. if i wanted to setup a docker registry auth where our secret is an arbitrary provider, we may `teller put` it by essentially calling `docker login ${registry:-} -u ${user} --password-stdin`. I think before i would have needed `docker-temp.t` and then overloaded `DOCKER_CONFIG` locations, or some shell logic.
