### ISSUE TITLE
Teller v1 to v2 migration guide?

### ISSUE THREAD

**Issue by d-a-n42** [tellerops/teller#282]
Hey,

thanks for providing this awesome project.

Homebrew just updated Teller on my machine to version 2. Nothing is working anymore. I could not find a changelog or migration guide. This is my current teller config:

```
project: project-id
carry_env: true

providers:
  dotenv:
    env_sync:
      path: .env.project-id
```

How does the config need to be changed for Teller 2.0?
