### ISSUE TITLE
Teller 2.0 aws_secretsmanager example/configuration help

### ISSUE THREAD

**Issue by pgpx** [tellerops/teller#283]
Hi, I've just installed Teller (2.0 from homebrew), but I cannot get it to work with secrets that I have in AWS secretsmanager, and I cannot find an example configuration to try either.

My teller.yaml:
```
providers:
  aws_secretsmanager_1:
    kind: aws_secretsmanager
    maps:
    - id: dev-gitlab
      path: my/aws/secrets/path
      keys:
        MY_SECRET: my-secret
```

But `teller show` just returns `Error: NOT FOUND /my/aws/secrets/path: not found`

And I've also tried variations on that, e.g.
```
providers:
  aws_secretsmanager_1:
    kind: aws_secretsmanager
    maps:
    - id: dev-gitlab
      path: my/aws/secrets/path/my-secret
      keys:
        MY_SECRET: ==
```

gives `Error: expected value at line 1 column 1`

But `aws secretsmanager get-secret-value --secret-id my/aws/secrets/path/my-secret` works (and the secret value is just a single string).  I'm obviously doing something wrong, but I'm not sure what!
