### ISSUE TITLE
Teller 2.0 does not support hashicorp namespace:

### ISSUE THREAD

**Issue by romans-ovo** [tellerops/teller#286]
While it's possible to my tokens with this:

```
curl \
        --header "X-Vault-Token: $VAULT_TOKEN" \
       --header "X-Vault-Namespace: my-namespace" \
        --request GET \
        ${VAULT_ADDR}v1/secret/data/my-path
```

Teller does not offer an option to specify a namespace. a handy way would be like this:

```
providers:
  vault:
    kind: hashicorp
    options:
      namespace: my-namespace
    maps:
     - id: local
       path: my-path
```

vaultrs has support for namespaces since 2022:
https://github.com/jmgilman/vaultrs/pull/41

I'm happy to submit PR for this.
