### ISSUE TITLE
Took me forever to figure out google secret manager

### ISSUE THREAD

**Issue by bdmorin** [tellerops/teller#291]
You guys have really complicated examples. 

For anyone else trying to use this with GSM, this format worked for me:

```
> cat .teller.yml
providers:
  google_secrets_manager:
    kind: google_secretmanager
    maps:
      - id: testsecret
        path: projects/1234567890
```

All the examples show the path as the full path `projects/1234567890/secrets/testsecret/versions/1`

or similar. Onboarding teller has been frustrating. 

There's only rust documentation, and I don't know rust. I haven't found a v2 tutorial on the internet that shows how this works yet. 

I'd like to offer help, should I just update the readme, or are you guys going to relaunch `tlr.dev`?

None of this is complaining, just pointing out new users may not be quick to adopt as there is lots of conflicting information. GPT4o doesn't know the new versions, so it's not helpful, and I can't train it with documentation as there's no formal doc or even man page. 

**How can I help?**

**Comment by vfarcic** [comment]
The example you posted returns all secrets in that Google project. Did you figure out how to limit it to a specific secret?

**Comment by bfrunza** [comment]
> The example you posted returns all secrets in that Google project. Did you figure out how to limit it to a specific secret?

@vfarcic as far as I could figure out, adding some keys will only fetch the mentioned secrets.
```
providers:
  google_secrets_manager:
    kind: google_secretmanager
    maps:
      - id: testsecret
        path: projects/1234567890
        keys:
          secret-name-1: ENV_VAR_NAME
          # or if you don't need to rename the secret
          secret-name-1: ==
```
