### ISSUE TITLE
aws secretsmanager returns GET dev/test/mytest: unhandled error

### ISSUE THREAD

**Issue by lelcuk** [tellerops/teller#304]
Hi
I am trying to retrieve a simple aws secret using teller 2.0.7 and im getting a constant error

.teller.yml
```
project: my_project
opts:
  stage: development

providers:
  aws_secrete:
    kind: aws_secretsmanager
    maps:
      - id: mykey
        path: dev/test/mytest
        keys:
          myKey: ==
```
when accessing the secret as `aws secretsmanager get-secret-value --secret-id dev/test/mytest`, I get a proper json

```
{
    "ARN": "******************************************:secret:dev/test/mytest-####",
    "Name": "dev/test/mytest",
    "VersionId": "************************",
    "SecretString": "{\"myKey\":\"mySecret\"}",
    "VersionStages": [
        "AWSCURRENT"
    ],
    "CreatedDate": "2024-08-19T10:33:12.709000+03:00"
}
```
but running `teller show` gets
```
Error: GET dev/test/mytest: unhandled error

Location:
    /build/source/teller-cli/src/cli.rs:296:23
```

what am I doing wrong?
aws config is:
```
[profile ##############]
sso_session = aaaaaaaaaaa
sso_account_id = ############
sso_role_name = PowerUserAccess
region = eu-central-1
[sso-session 'aaaaaaaaaaa']
sso_start_url = https://????????.awsapps.com/start
sso_region = eu-central-1
sso_registration_scopes = sso:account:access
```

TIA
