### ISSUE TITLE
Ansible Vault

### ISSUE THREAD

**Issue by TheLastProject** [tellerops/teller#85]
## Details
- Name: Ansible Vault
- URL: https://docs.ansible.com/ansible/latest/user_guide/vault.html
- Modes: read+write
- GitHub projects: https://github.com/ansible/ansible
- API Documentation: https://docs.ansible.com/ansible/latest/user_guide/vault.html

It would be great if Ansible Vault could be supported. That way it would be easy to re-use Ansible Vault secrets as environment variables. My example use case would be a setup where Ansible talks to an API and thus that API key is in Ansible Vault, and Terraform needs to talk to this API as well.

**Comment by jondot** [comment]
Thanks for the request, this is great information for us :)
I've skimmed the ansible vault spec. Looks like we can read the YAML including the format https://docs.ansible.com/ansible/latest/user_guide/vault.html#ansible-vault-payload-format-1-1-1-2 , and continue from there.

Since I'm wondering about where the encryption key is stored and managed, since looks like it's required to decrypt, I'd be happy to also hear about how you use ansible vault today [specifically this document shows a few ways](https://docs.ansible.com/ansible/latest/user_guide/vault.html#managing-vault-passwords). Or a link to typical usage pattern that you prefer as a best practice would be great.

**Comment by TheLastProject** [comment]
> Looks like we can read the YAML including the format https://docs.ansible.com/ansible/latest/user_guide/vault.html#ansible-vault-payload-format-1-1-1-2 , and continue from there.

That looks about right. There also seem to be several libraries existing already, but the spec indeed seems simple enough to not require libraries if not desirable.

> since looks like it's required to decrypt

It indeed is.

> I'd be happy to also hear about how you use ansible vault today [specifically this document shows a few ways](https://docs.ansible.com/ansible/latest/user_guide/vault.html#managing-vault-passwords). Or a link to typical usage pattern that you prefer as a best practice would be great.

Wall of text summarizing my experiences with Ansible Vault incoming :)

### Vault usage patterns

Most commonly people put the Vault decryption password in some file on their system (this is a plain text file containing the password as is). For example, imagine a file like `~/.ansible_vault_pass` containing a string like `my_secret_password`. To me personally, this always felt somewhat icky as you're storing a secret as plain text, but it is the most common and suggested "Ansible way". In an Ansible run, one would use a command like following: `ansible-playbook playbook.yml --vault-password-file ~/.ansible_vault`.

Another very common possibility is to make Ansible ask for the Ansible Vault password: `ansible-playbook playbook.yml --ask-vault-pass`. This is generally the way I personally go about things because even though this does mean tedious copy-pasting, it means I can take the password from a password manager without messing with random scripts.

For those who do integrate Ansible Vault with another password manager, they're usually usually [expected to use scripts](https://docs.ansible.com/ansible/latest/user_guide/vault.html#storing-passwords-in-third-party-tools-with-vault-password-client-scripts) although implementing this support only in Ansible instead of more generically like #44 suggest would seem strange to me. Even then, in most cases using output of another Teller-supported source seems to me like it should cover the vast majority of use cases for this.

If possible, the most awesome thing would be if you could refer to an existing (Teller) environment variable so you could for example put your Ansible Vault decryption password in gopass or whatever but I'm too new to know if Teller is set up for something like that. To support the setup most people are likely already using, reading the password from a plain text file is most likely required.

### Example configs

So, summarizing, I'm expecting an MVP to be something like this:
```
providers:
  ansible_vault:
    env_sync:
      path: ansible/vars/vault_{{stage}}.yml
      passphrase:
        path: ~/.ansible_vault
```

However, even cleaner could be to have a plain file provider and refer to that, if Teller supports something like that:
```
providers:
  plain:
    env:
      ANSIBLE_VAULT_PASSPHRASE:
        path: ~/.ansible_vault
  ansible_vault:
    env_sync:
      path: ansible/vars/vault_{{stage}}.yml
      passphrase: {{ANSIBLE_VAULT_PASSPHRASE}}
```

Referring to the output of another provider would also make it very clean to store your Ansible Vault decryption password in a safe way:
```
providers:
  gopass:
    env:
      ANSIBLE_VAULT_PASSPHRASE:
        path: ansible/{{stage}}
  ansible_vault:
    env_sync:
      path: ansible/vars/vault_{{stage}}.yml
      passphrase: {{ANSIBLE_VAULT_PASSPHRASE}}
```

Hope that makes sense!
